backend:
  name: github
  repo: jakubmaslon/metalsmith-netlify # Path to your Github repository
  branch: master # Branch to update

media_folder: "src/assets/images/uploads" # Media files will be stored here
public_folder: "/images/uploads" # The src attribute for uploaded media

collections:
  - name: "index"
    label: "Label"
    folder: "src/html/"
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title_EN", widget: "string"}
      - {label: "Title_AR", name: "title_AR", widget: "string"}
      - {label: "customfield", name: "customfield", widget: "string"}